"""add account nickname

Revision ID: ccd3c3f4b047
Revises: 70484467d522
Create Date: 2026-09-23 21:23:56.269397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd3c3f4b047'
down_revision: Union[str, None] = '70484467d522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('nickname', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'nickname')
    # ### end Alembic commands ###
