"""initial schema

Revision ID: a8129b68f00d
Revises: 
Create Date: 2026-09-23 21:22:37.407872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8129b68f00d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_service'), 'request_logs', ['service'], unique=False)
    op.create_index(op.f('ix_request_logs_ts'), 'request_logs', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_ts'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_service'), table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###
